language: python

cache:
  - pip
  - ccache

matrix:
  include:
    - os: linux
      python: "2.7"
    - os: linux
      python: "3.6"

script:
  - flake8

install:
  - pip install -U pip wheel
  - pip install -r ./tools/requirements_test.txt

sudo: false