language: python

cache:
  - pip
  - ccache

matrix:
  include:
    - os: linux
      python: "3.6"

script:
  - ./test/test_rir.py
  - flake8 pyimagesource

install:
  - pip install -U pip wheel
  - pip install -e .[test]

sudo: false